name: Build and Release APK

on:
  push:
    tags:
      - '*.*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Make Gradle executable
      run: chmod +x ./gradlew
    - name: Build Release APK
      run: ./gradlew assembleRelease
    - uses: r0adkll/sign-android-release@v1
      id: signing
      name: Sign app APK
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
    
    - name: Releasing using Hub
      uses: gnuhry/action-release-releaseapk@master
      env:
       GITHUB_TOKEN: ${{ secrets.TOKEN }}
       #APP_FOLDER: app
       FILE: ${{steps.signing.outputs.signedReleaseFile}}
       #RELEASE_TITLE: RELEASE 
       #VERSION_NAME : ${{ github.ref }}  
